import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { GetList } from "../core/service/genaric";
import { machine } from "../core/util/schemas";
import {
  Space,
  Card,
  Empty,
  Button,
  Image,
  Pagination,
  Input,
  Layout,
} from "antd";
const { Search } = Input;
import { Title, Container } from "./pages.style";
const { Header } = Layout;

const { Meta } = Card;

export default function Home() {
  const router = useRouter();
  const [machineList, setMachineList] = useState([]);
  const [showList, setShowList] = useState([]);
  const [searchData, setSearchData] = useState([]);
  const [pagination, setPagination] = useState({
    perPage: 6,
    page: 1,
    total_page: 10,
  });

  useEffect(() => {
    getMachineList();
  }, []);

  function getMachineList() {
    GetList(machine)
      .then((response) => {
        console.log("response", response);
        if (response.code === 200) {
          setMachineList(response.data);
          filterData(1, response.data);
        }
      })
      .catch((err) => {});
  }

  function handlePaginationChange(e, list) {
    filterData(e, list);
  }

  function filterData(value, machineList) {
    const temp = [];
    const index = value - 1;
    for (
      let i = index * 10;
      i < (value * 10 > machineList.length ? machineList.length : value * 10);
      i++
    ) {
      temp.push(machineList[i]);
    }
    setShowList(temp);
    setPagination({
      perPage: 10,
      page: value,
      total: searchData.length ? searchData.length : machineList.length,
    });
  }

  function onSearch(e) {
    const result = machineList.filter(
      (value) =>
        value.machine_name
          .toLowerCase()
          .indexOf(e.target.value.toLowerCase()) !== -1
    );

    setShowList(result);
    filterData(1, result);
    setSearchData(result);
    setPagination({ perPage: 6, page: 1, total: result.length });
  }

  return (
    <div>
      <Head>
        <title>[WEB] Vending Machine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        style={{
          height: "100px",
          justifyContent: "space-between",
          display: "flex",
        }}
      >
        <Space align="baseline" style={{ marginTop: 15 }}>
          <Title style={{ color: "white" }}>Drink Vending Machine</Title>
        </Space>
      </Header>
      <main style={{ padding: 40 }}>
        <Space align="baseline">
          <Title>Drink Vending Machine List</Title>
          <Search
            placeholder="Name"
            onChange={onSearch}
            style={{ width: 300, marginTop: -8, marginLeft: 10 }}
          />
        </Space>
        <Container>
          <Space
            size={[16, 16]}
            wrap
            align="center"
            style={{
              padding: "60px 0 60px 80px",
            }}
          >
            {!showList.length ? (
              <div
                style={{
                  display: "flex",
                  width: "96vw",
                  // height: "100vh",
                  justifyContent: "center",
                }}
              >
                <Empty />
              </div>
            ) : (
              showList.map((machine, index) => {
                return (
                  <Card
                    key={index}
                    hoverable
                    style={{
                      width: 320,
                      textAlign: "center",
                      borderRadius: 15,
                    }}
                    cover={
                      <Image
                        width={300}
                        height={300}
                        preview={false}
                        alt="machine"
                        src={machine.machine_image}
                        style={{ padding: 20 }}
                      />
                    }
                  >
                    <Meta
                      className="custom-ant-meta-description"
                      title={machine.machine_name}
                      description={machine.machine_detail}
                    />
                    <Button
                      style={{ marginTop: "20px" }}
                      onClick={() => router.push(`/machine/${machine._id}`)}
                    >
                      ENTER
                    </Button>
                  </Card>
                );
              })
            )}
          </Space>
        </Container>
        <div style={{ width: "100%", textAlign: "right", marginTop: 10 }}>
          <Pagination
            current={pagination.page}
            defaultCurrent={1}
            total={pagination.total}
            pageSize={pagination.perPage}
            style={{ marginTop: 20, textAlign: "right" }}
            onChange={(e) =>
              handlePaginationChange(
                e,
                searchData.length ? searchData : machineList
              )
            }
          />
        </div>
      </main>
    </div>
  );
}
